version: "3.8"
services:
  proxy:
    restart: always
    image: nginx
    depends_on:
      - health
      - apiserver-web
      - registry
      - services-registry
      - sp-registry
      - settings
      - dns-mgmt
      - billing
    volumes:
      - ../../proxy:/etc/nginx/templates
    ports:
      - 8080:8080
    networks:
      - proxy
  health:
    container_name: health-service
    restart: always
    image: ghcr.io/slntopp/nocloud/health:dev-billing
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      PROBABLES: registry:8080,billing:8080,services-registry:8080,sp-registry:8080,settings:8080,dns-mgmt:8080,edge:8080
    networks:
      - proxy
      - grpc-internal
  apiserver-web:
    container_name: apiserver-web
    restart: always
    depends_on:
      - registry
      - services-registry
      - sp-registry
      - settings
      - dns-mgmt
      - billing
      - edge
    environment:
      LOG_LEVEL: -1
      APISERVER_HOST: proxy:8080
    ports:
      - 8000:8000 # REST-API
    networks:
      - proxy
      - grpc-internal
  registry:
    container_name: registry
    restart: always
    image: ghcr.io/slntopp/nocloud/registry:latest
    environment:
      LOG_LEVEL: -1
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      NOCLOUD_ROOT_PASSWORD: "${NOCLOUD_ROOT_PASS}"
      SIGNING_KEY: "${SIGNING_KEY}"
      SETTINGS_HOST: settings:8080
    depends_on:
      - db
    networks:
      - proxy
      - arangodb
      - grpc-internal
    links:
      - db
  services-registry:
    container_name: services-registry
    restart: always
    image: ghcr.io/slntopp/nocloud/services-registry:dev-billing
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      DRIVERS: driver-ione:8080
      SETTINGS_HOST: settings:8080
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    depends_on:
      - db
      - driver-ione
    networks:
      - proxy
      - arangodb
      - grpc-internal
      - mq
    links:
      - db
  sp-registry:
    container_name: sp-registry
    restart: always
    image: ghcr.io/slntopp/nocloud/sp-registry:dev-schema
    depends_on:
      - db
      - driver-ione
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      DRIVERS: driver-ione:8080
      SETTINGS_HOST: settings:8080
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    networks:
      - proxy
      - arangodb
      - grpc-internal
      - mq
    links:
      - db
  edge:
    container_name: edge
    restart: always
    image: ghcr.io/slntopp/nocloud/edge:latest
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    networks:
      - proxy
      - mq
    links:
      - db

  dns-mgmt:
    restart: always
    image: ghcr.io/slntopp/nocloud/dns-mgmt:latest
    depends_on:
      - redis_settings
    networks:
      - proxy
      - grpc-internal
      - redis
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      REDIS_HOST: redis_settings:6379
  settings:
    restart: always
    depends_on:
      - redis_settings
    image: ghcr.io/slntopp/nocloud/settings:latest
    networks:
      - proxy
      - grpc-internal
      - redis
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      REDIS_HOST: redis_settings:6379
  redis_settings:
    image: redis
    restart: always
    command: redis-server --save 60 1
    networks:
      - redis
    volumes:
      - redis-settings-data:/data

  billing:
    container_name: billing
    restart: always
    depends_on:
      - db
      - settings
    image: ghcr.io/slntopp/nocloud/billing:dev-billing
    networks:
      - proxy
      - arangodb
      - grpc-internal
      - mq
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      SETTINGS_HOST: settings:8080
    links:
      - db

  driver-ione:
    container_name: driver
    restart: always
    image: ghcr.io/slntopp/nocloud-driver-ione:latest
    networks:
      - grpc-internal
      - mq
    environment:
      DRIVER_TYPE_KEY: ione
      SIGNING_KEY: "${SIGNING_KEY}"
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      LOG_LEVEL: -1

  db:
    container_name: database-master
    restart: always
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3
    networks:
      - arangodb
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"

networks:
  proxy:
    driver: bridge
  grpc-internal:
  arangodb:
    driver: bridge
  redis:
    driver: bridge
  mq:
    driver: bridge

volumes:
  redis-settings-data:
  data:
