name: Checks

on: ["push", "pull_request"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Static Check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          min-go-version: 1.18
