name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:
    inputs:
      images:
        description: 'comma-separated Images Names list'
        required: true
        default: base

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged containers older than a day
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.inputs.images }}
          cut-off: A day ago UTC
          account-type: personal
          untagged-only: true
          token: ${{ secrets.PACKAGES_PAT }}

      - name: Delete dev containers older than two week
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.inputs.images }}
          cut-off: 2 weeks ago UTC
          account-type: personal
          filter-tags: dev-*
          filter-include-untagged: true
          token: ${{ secrets.PACKAGES_PAT }}
