name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:
    inputs:
      images:
        description: 'comma-separated Images Names list'
        default: nocloud/base
env:
  images: ${{ github.event.inputs.images }} || "nocloud/base, nocloud/billing, nocloud/edge, nocloud/settings, nocloud/dns-mgmt, nocloud/apiserver-web, nocloud/services-registry, nocloud/health, nocloud/registry, nocloud/sp-registry"

jobs:
  clean-ghcr:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Untagged Images (> 1 day)
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.inputs.images }}
          cut-off: A day ago UTC
          account-type: personal
          untagged-only: true
          token: ${{ secrets.PACKAGES_PAT }}

      - name: Dev Images (> 2 weeks)
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.inputs.images }}
          cut-off: 2 weeks ago UTC
          account-type: personal
          filter-tags: dev-*
          filter-include-untagged: true
          token: ${{ secrets.PACKAGES_PAT }}
